version: '3.8'

services:

  nodejs:
    build: .
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: >
      bash -c "cp -r -f /var/www/custom/. /var/www/public
      && yarn
      && quasar dev"
    depends_on:
      - php
    ports:
      - 8080:8080
    networks:
      - network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./:/var/www
      - ./dev/nginx/conf.d:/etc/nginx/conf.d
      - ./dev/nginx/logs:/var/log/nginx
    depends_on:
      - php 
    ports:
      - 80:80
    networks:
      - network

  php:
    build: ./dev/php/
    container_name: php
    restart: unless-stopped
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./:/var/www
      - ./dev/.ssh:~/.ssh
      - ./dev/php/php.ini:/usr/local/etc/php/php.ini
      - ./dev/php/supervisor.d:/etc/supervisor.d
    working_dir: /var/www/
    depends_on:
      - mysql
    networks:
      - network

  adminer:
    image: adminer:fastcgi
    restart: always
    environment:
      - ADMINER_PLUGINS=${ADMINER_PLUGINS}
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME}
      - MYSQL_HOST=${MYSQL_HOST}
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

  mysql:
    image: mysql:8.0.29
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    hostname: ${MYSQL_HOST}
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dev/mysql/data:/var/lib/mysql
      - ./dev/mysql/conf.d:/etc/mysql/conf.d
      - ./dev/mysql/logs:/var/log/mysql
      - ./dev/mysql/dump:/dump
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - network

  postgres:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
        - network

  mongo:
    image: mongo:4.2
    container_name: mongo
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
      - ./mongo/dump:/dump
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - network

networks:
  network:
    driver: bridge
